### ISSUE TITLE
show_list broken

### ISSUE THREAD

**Issue by ryanmerolle** [networktocode/nornir-pyntc#15]
### Environment
* Python version:  3.11.0
* nornir-pyntc version:  1.0.1

### Expected Behavior

pyntc_show_list works.

### Observed Behavior

pyntc_show_list broke when the underlying pyntc show_list() was deprecated.

output now shows
```
/usr/local/lib/python3.11/site-packages/pyntc/devices/eos_device.py:563: DeprecationWarning: show_list() is deprecated; use show().
  warnings.warn("show_list() is deprecated; use show().", DeprecationWarning)
vvvv ceos1: pyntc_show_list ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv INFO
^^^^ END pyntc_show_list ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vvvv ceos2: pyntc_show_list ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv INFO
^^^^ END pyntc_show_list ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Options to address

1. Deprecate pyntc_show_list and update documentation accordingly
2. Fix pyntc_show_list and correct integration tests to catch this sort of item in the future.

**Comment by jeffkala** [comment]
thanks @ryanmerolle for this report.

**Comment by jeffkala** [comment]
show_list was deprecated and removed in 1.0.0 of pyntc and 2.0.0 of this repo.
